/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// BulkGetAvailableCommandsRequest
    /// </summary>
    [DataContract(Name = "BulkGetAvailableCommandsRequest")]
    public partial class BulkGetAvailableCommandsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkGetAvailableCommandsRequest" /> class.
        /// </summary>
        /// <param name="processIds">processIds.</param>
        /// <param name="identityIds">identityIds.</param>
        /// <param name="commandNameFilter">commandNameFilter.</param>
        /// <param name="culture">culture.</param>
        /// <param name="conditionCheck">conditionCheck.</param>
        /// <param name="maxDegreeOfParallelism">maxDegreeOfParallelism.</param>
        public BulkGetAvailableCommandsRequest(List<Guid> processIds = default(List<Guid>), List<string> identityIds = default(List<string>), string commandNameFilter = default(string), string culture = default(string), bool conditionCheck = default(bool), int? maxDegreeOfParallelism = default(int?))
        {
            this.ProcessIds = processIds;
            this.IdentityIds = identityIds;
            this.CommandNameFilter = commandNameFilter;
            this.Culture = culture;
            this.ConditionCheck = conditionCheck;
            this.MaxDegreeOfParallelism = maxDegreeOfParallelism;
        }

        /// <summary>
        /// Gets or Sets ProcessIds
        /// </summary>
        [DataMember(Name = "processIds", EmitDefaultValue = true)]
        public List<Guid> ProcessIds { get; set; }

        /// <summary>
        /// Gets or Sets IdentityIds
        /// </summary>
        [DataMember(Name = "identityIds", EmitDefaultValue = true)]
        public List<string> IdentityIds { get; set; }

        /// <summary>
        /// Gets or Sets CommandNameFilter
        /// </summary>
        [DataMember(Name = "commandNameFilter", EmitDefaultValue = true)]
        public string CommandNameFilter { get; set; }

        /// <summary>
        /// Gets or Sets Culture
        /// </summary>
        [DataMember(Name = "culture", EmitDefaultValue = true)]
        public string Culture { get; set; }

        /// <summary>
        /// Gets or Sets ConditionCheck
        /// </summary>
        [DataMember(Name = "conditionCheck", EmitDefaultValue = true)]
        public bool ConditionCheck { get; set; }

        /// <summary>
        /// Gets or Sets MaxDegreeOfParallelism
        /// </summary>
        [DataMember(Name = "maxDegreeOfParallelism", EmitDefaultValue = true)]
        public int? MaxDegreeOfParallelism { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkGetAvailableCommandsRequest {\n");
            sb.Append("  ProcessIds: ").Append(ProcessIds).Append("\n");
            sb.Append("  IdentityIds: ").Append(IdentityIds).Append("\n");
            sb.Append("  CommandNameFilter: ").Append(CommandNameFilter).Append("\n");
            sb.Append("  Culture: ").Append(Culture).Append("\n");
            sb.Append("  ConditionCheck: ").Append(ConditionCheck).Append("\n");
            sb.Append("  MaxDegreeOfParallelism: ").Append(MaxDegreeOfParallelism).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
