/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// BulkExecuteCommandRequest
    /// </summary>
    [DataContract(Name = "BulkExecuteCommandRequest")]
    public partial class BulkExecuteCommandRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkExecuteCommandRequest" /> class.
        /// </summary>
        /// <param name="commands">commands.</param>
        /// <param name="identityId">identityId.</param>
        /// <param name="impersonatedIdentityId">impersonatedIdentityId.</param>
        /// <param name="checkRestrictions">checkRestrictions.</param>
        /// <param name="maxDegreeOfParallelism">maxDegreeOfParallelism.</param>
        public BulkExecuteCommandRequest(List<WorkflowCommand> commands = default(List<WorkflowCommand>), string identityId = default(string), string impersonatedIdentityId = default(string), bool checkRestrictions = default(bool), int? maxDegreeOfParallelism = default(int?))
        {
            this.Commands = commands;
            this.IdentityId = identityId;
            this.ImpersonatedIdentityId = impersonatedIdentityId;
            this.CheckRestrictions = checkRestrictions;
            this.MaxDegreeOfParallelism = maxDegreeOfParallelism;
        }

        /// <summary>
        /// Gets or Sets Commands
        /// </summary>
        [DataMember(Name = "commands", EmitDefaultValue = true)]
        public List<WorkflowCommand> Commands { get; set; }

        /// <summary>
        /// Gets or Sets IdentityId
        /// </summary>
        [DataMember(Name = "identityId", EmitDefaultValue = true)]
        public string IdentityId { get; set; }

        /// <summary>
        /// Gets or Sets ImpersonatedIdentityId
        /// </summary>
        [DataMember(Name = "impersonatedIdentityId", EmitDefaultValue = true)]
        public string ImpersonatedIdentityId { get; set; }

        /// <summary>
        /// Gets or Sets CheckRestrictions
        /// </summary>
        [DataMember(Name = "checkRestrictions", EmitDefaultValue = true)]
        public bool CheckRestrictions { get; set; }

        /// <summary>
        /// Gets or Sets MaxDegreeOfParallelism
        /// </summary>
        [DataMember(Name = "maxDegreeOfParallelism", EmitDefaultValue = true)]
        public int? MaxDegreeOfParallelism { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkExecuteCommandRequest {\n");
            sb.Append("  Commands: ").Append(Commands).Append("\n");
            sb.Append("  IdentityId: ").Append(IdentityId).Append("\n");
            sb.Append("  ImpersonatedIdentityId: ").Append(ImpersonatedIdentityId).Append("\n");
            sb.Append("  CheckRestrictions: ").Append(CheckRestrictions).Append("\n");
            sb.Append("  MaxDegreeOfParallelism: ").Append(MaxDegreeOfParallelism).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
