/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// BulkCreateInstanceRequest
    /// </summary>
    [DataContract(Name = "BulkCreateInstanceRequest")]
    public partial class BulkCreateInstanceRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkCreateInstanceRequest" /> class.
        /// </summary>
        /// <param name="createInstanceParamsList">createInstanceParamsList.</param>
        /// <param name="maxDegreeOfParallelism">maxDegreeOfParallelism.</param>
        public BulkCreateInstanceRequest(List<CreateInstanceParamsItem> createInstanceParamsList = default(List<CreateInstanceParamsItem>), int? maxDegreeOfParallelism = default(int?))
        {
            this.CreateInstanceParamsList = createInstanceParamsList;
            this.MaxDegreeOfParallelism = maxDegreeOfParallelism;
        }

        /// <summary>
        /// Gets or Sets CreateInstanceParamsList
        /// </summary>
        [DataMember(Name = "createInstanceParamsList", EmitDefaultValue = true)]
        public List<CreateInstanceParamsItem> CreateInstanceParamsList { get; set; }

        /// <summary>
        /// Gets or Sets MaxDegreeOfParallelism
        /// </summary>
        [DataMember(Name = "maxDegreeOfParallelism", EmitDefaultValue = true)]
        public int? MaxDegreeOfParallelism { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkCreateInstanceRequest {\n");
            sb.Append("  CreateInstanceParamsList: ").Append(CreateInstanceParamsList).Append("\n");
            sb.Append("  MaxDegreeOfParallelism: ").Append(MaxDegreeOfParallelism).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
