/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// Defines DatabaseStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DatabaseStatus
    {
        /// <summary>
        /// Enum Connected for value: Connected
        /// </summary>
        [EnumMember(Value = "Connected")]
        Connected = 1,

        /// <summary>
        /// Enum ConnectionFailed for value: ConnectionFailed
        /// </summary>
        [EnumMember(Value = "ConnectionFailed")]
        ConnectionFailed = 2
    }

}
