/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// DeleteAllSubprocessesResponse
    /// </summary>
    [DataContract(Name = "DeleteAllSubprocessesResponse")]
    public partial class DeleteAllSubprocessesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteAllSubprocessesResponse" /> class.
        /// </summary>
        /// <param name="deletedSubprocessesCount">deletedSubprocessesCount.</param>
        public DeleteAllSubprocessesResponse(int deletedSubprocessesCount = default(int))
        {
            this.DeletedSubprocessesCount = deletedSubprocessesCount;
        }

        /// <summary>
        /// Gets or Sets DeletedSubprocessesCount
        /// </summary>
        [DataMember(Name = "deletedSubprocessesCount", EmitDefaultValue = false)]
        public int DeletedSubprocessesCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteAllSubprocessesResponse {\n");
            sb.Append("  DeletedSubprocessesCount: ").Append(DeletedSubprocessesCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
