/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// ExecuteCommandResponse
    /// </summary>
    [DataContract(Name = "ExecuteCommandResponse")]
    public partial class ExecuteCommandResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExecuteCommandResponse" /> class.
        /// </summary>
        /// <param name="commandName">commandName.</param>
        /// <param name="wasExecuted">wasExecuted.</param>
        /// <param name="processInstance">processInstance.</param>
        /// <param name="message">message.</param>
        public ExecuteCommandResponse(string commandName = default(string), bool wasExecuted = default(bool), ProcessInstance processInstance = default(ProcessInstance), string message = default(string))
        {
            this.CommandName = commandName;
            this.WasExecuted = wasExecuted;
            this.ProcessInstance = processInstance;
            this.Message = message;
        }

        /// <summary>
        /// Gets or Sets CommandName
        /// </summary>
        [DataMember(Name = "commandName", EmitDefaultValue = true)]
        public string CommandName { get; set; }

        /// <summary>
        /// Gets or Sets WasExecuted
        /// </summary>
        [DataMember(Name = "wasExecuted", EmitDefaultValue = true)]
        public bool WasExecuted { get; set; }

        /// <summary>
        /// Gets or Sets ProcessInstance
        /// </summary>
        [DataMember(Name = "processInstance", EmitDefaultValue = false)]
        public ProcessInstance ProcessInstance { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExecuteCommandResponse {\n");
            sb.Append("  CommandName: ").Append(CommandName).Append("\n");
            sb.Append("  WasExecuted: ").Append(WasExecuted).Append("\n");
            sb.Append("  ProcessInstance: ").Append(ProcessInstance).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
