/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// InboxEntryModel
    /// </summary>
    [DataContract(Name = "InboxEntryModel")]
    public partial class InboxEntryModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InboxEntryModel" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="processId">processId.</param>
        /// <param name="identityId">identityId.</param>
        /// <param name="addingDate">addingDate.</param>
        /// <param name="availableCommands">availableCommands.</param>
        public InboxEntryModel(Guid id = default(Guid), Guid processId = default(Guid), string identityId = default(string), DateTimeOffset addingDate = default(DateTimeOffset), List<string> availableCommands = default(List<string>))
        {
            this.Id = id;
            this.ProcessId = processId;
            this.IdentityId = identityId;
            this.AddingDate = addingDate;
            this.AvailableCommands = availableCommands;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets ProcessId
        /// </summary>
        [DataMember(Name = "processId", EmitDefaultValue = false)]
        public Guid ProcessId { get; set; }

        /// <summary>
        /// Gets or Sets IdentityId
        /// </summary>
        [DataMember(Name = "identityId", EmitDefaultValue = true)]
        public string IdentityId { get; set; }

        /// <summary>
        /// Gets or Sets AddingDate
        /// </summary>
        [DataMember(Name = "addingDate", EmitDefaultValue = false)]
        public DateTimeOffset AddingDate { get; set; }

        /// <summary>
        /// Gets or Sets AvailableCommands
        /// </summary>
        [DataMember(Name = "availableCommands", EmitDefaultValue = true)]
        public List<string> AvailableCommands { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InboxEntryModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ProcessId: ").Append(ProcessId).Append("\n");
            sb.Append("  IdentityId: ").Append(IdentityId).Append("\n");
            sb.Append("  AddingDate: ").Append(AddingDate).Append("\n");
            sb.Append("  AvailableCommands: ").Append(AvailableCommands).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
