/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// Defines ProcessStatusAvailableToSet
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProcessStatusAvailableToSet
    {
        /// <summary>
        /// Enum Initialized for value: Initialized
        /// </summary>
        [EnumMember(Value = "Initialized")]
        Initialized = 1,

        /// <summary>
        /// Enum Running for value: Running
        /// </summary>
        [EnumMember(Value = "Running")]
        Running = 2,

        /// <summary>
        /// Enum Idled for value: Idled
        /// </summary>
        [EnumMember(Value = "Idled")]
        Idled = 3,

        /// <summary>
        /// Enum Finalized for value: Finalized
        /// </summary>
        [EnumMember(Value = "Finalized")]
        Finalized = 4,

        /// <summary>
        /// Enum Terminated for value: Terminated
        /// </summary>
        [EnumMember(Value = "Terminated")]
        Terminated = 5,

        /// <summary>
        /// Enum Error for value: Error
        /// </summary>
        [EnumMember(Value = "Error")]
        Error = 6
    }

}
