/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// ReadinessResponse
    /// </summary>
    [DataContract(Name = "ReadinessResponse")]
    public partial class ReadinessResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadinessResponse" /> class.
        /// </summary>
        /// <param name="isHealthy">isHealthy.</param>
        /// <param name="message">message.</param>
        /// <param name="tenantStatuses">tenantStatuses.</param>
        public ReadinessResponse(bool isHealthy = default(bool), string message = default(string), List<TenantStatus> tenantStatuses = default(List<TenantStatus>))
        {
            this.IsHealthy = isHealthy;
            this.Message = message;
            this.TenantStatuses = tenantStatuses;
        }

        /// <summary>
        /// Gets or Sets IsHealthy
        /// </summary>
        [DataMember(Name = "isHealthy", EmitDefaultValue = true)]
        public bool IsHealthy { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets TenantStatuses
        /// </summary>
        [DataMember(Name = "tenantStatuses", EmitDefaultValue = true)]
        public List<TenantStatus> TenantStatuses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReadinessResponse {\n");
            sb.Append("  IsHealthy: ").Append(IsHealthy).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  TenantStatuses: ").Append(TenantStatuses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
