/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// Defines RuntimeRunningStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RuntimeRunningStatus
    {
        /// <summary>
        /// Enum Stopped for value: Stopped
        /// </summary>
        [EnumMember(Value = "Stopped")]
        Stopped = 1,

        /// <summary>
        /// Enum Running for value: Running
        /// </summary>
        [EnumMember(Value = "Running")]
        Running = 2,

        /// <summary>
        /// Enum RunningCold for value: RunningCold
        /// </summary>
        [EnumMember(Value = "RunningCold")]
        RunningCold = 3
    }

}
