/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// Defines RuntimeStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RuntimeStatus
    {
        /// <summary>
        /// Enum Alive for value: Alive
        /// </summary>
        [EnumMember(Value = "Alive")]
        Alive = 1,

        /// <summary>
        /// Enum Restore for value: Restore
        /// </summary>
        [EnumMember(Value = "Restore")]
        Restore = 2,

        /// <summary>
        /// Enum SelfRestore for value: SelfRestore
        /// </summary>
        [EnumMember(Value = "SelfRestore")]
        SelfRestore = 3,

        /// <summary>
        /// Enum Dead for value: Dead
        /// </summary>
        [EnumMember(Value = "Dead")]
        Dead = 4,

        /// <summary>
        /// Enum Terminated for value: Terminated
        /// </summary>
        [EnumMember(Value = "Terminated")]
        Terminated = 5,

        /// <summary>
        /// Enum Single for value: Single
        /// </summary>
        [EnumMember(Value = "Single")]
        Single = 6
    }

}
