/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// Defines SchemeField
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SchemeField
    {
        /// <summary>
        /// Enum Code for value: Code
        /// </summary>
        [EnumMember(Value = "Code")]
        Code = 1,

        /// <summary>
        /// Enum Scheme for value: Scheme
        /// </summary>
        [EnumMember(Value = "Scheme")]
        Scheme = 2,

        /// <summary>
        /// Enum CanBeInlined for value: CanBeInlined
        /// </summary>
        [EnumMember(Value = "CanBeInlined")]
        CanBeInlined = 3,

        /// <summary>
        /// Enum InlinedSchemes for value: InlinedSchemes
        /// </summary>
        [EnumMember(Value = "InlinedSchemes")]
        InlinedSchemes = 4,

        /// <summary>
        /// Enum Tags for value: Tags
        /// </summary>
        [EnumMember(Value = "Tags")]
        Tags = 5
    }

}
