/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// SetProcessNewStatusRequest
    /// </summary>
    [DataContract(Name = "SetProcessNewStatusRequest")]
    public partial class SetProcessNewStatusRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ProcessStatus
        /// </summary>
        [DataMember(Name = "processStatus", EmitDefaultValue = false)]
        public ProcessStatusAvailableToSet? ProcessStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetProcessNewStatusRequest" /> class.
        /// </summary>
        /// <param name="processId">processId.</param>
        /// <param name="processStatus">processStatus.</param>
        /// <param name="suppressEvent">suppressEvent.</param>
        public SetProcessNewStatusRequest(Guid processId = default(Guid), ProcessStatusAvailableToSet? processStatus = default(ProcessStatusAvailableToSet?), bool suppressEvent = default(bool))
        {
            this.ProcessId = processId;
            this.ProcessStatus = processStatus;
            this.SuppressEvent = suppressEvent;
        }

        /// <summary>
        /// Gets or Sets ProcessId
        /// </summary>
        [DataMember(Name = "processId", EmitDefaultValue = false)]
        public Guid ProcessId { get; set; }

        /// <summary>
        /// Gets or Sets SuppressEvent
        /// </summary>
        [DataMember(Name = "suppressEvent", EmitDefaultValue = true)]
        public bool SuppressEvent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetProcessNewStatusRequest {\n");
            sb.Append("  ProcessId: ").Append(ProcessId).Append("\n");
            sb.Append("  ProcessStatus: ").Append(ProcessStatus).Append("\n");
            sb.Append("  SuppressEvent: ").Append(SuppressEvent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
