/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// Defines StatusField
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum StatusField
    {
        /// <summary>
        /// Enum Id for value: Id
        /// </summary>
        [EnumMember(Value = "Id")]
        Id = 1,

        /// <summary>
        /// Enum Status for value: Status
        /// </summary>
        [EnumMember(Value = "Status")]
        Status = 2,

        /// <summary>
        /// Enum Lock for value: Lock
        /// </summary>
        [EnumMember(Value = "Lock")]
        Lock = 3,

        /// <summary>
        /// Enum RuntimeId for value: RuntimeId
        /// </summary>
        [EnumMember(Value = "RuntimeId")]
        RuntimeId = 4,

        /// <summary>
        /// Enum SetTime for value: SetTime
        /// </summary>
        [EnumMember(Value = "SetTime")]
        SetTime = 5
    }

}
