/*
 * Workflow Engine API
 *
 * A Workflow Engine Web API
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WorkflowApi.Client.Client.OpenAPIDateConverter;

namespace WorkflowApi.Client.Model
{
    /// <summary>
    /// Defines TimerField
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TimerField
    {
        /// <summary>
        /// Enum Id for value: Id
        /// </summary>
        [EnumMember(Value = "Id")]
        Id = 1,

        /// <summary>
        /// Enum ProcessId for value: ProcessId
        /// </summary>
        [EnumMember(Value = "ProcessId")]
        ProcessId = 2,

        /// <summary>
        /// Enum RootProcessId for value: RootProcessId
        /// </summary>
        [EnumMember(Value = "RootProcessId")]
        RootProcessId = 3,

        /// <summary>
        /// Enum Name for value: Name
        /// </summary>
        [EnumMember(Value = "Name")]
        Name = 4,

        /// <summary>
        /// Enum NextExecutionDateTime for value: NextExecutionDateTime
        /// </summary>
        [EnumMember(Value = "NextExecutionDateTime")]
        NextExecutionDateTime = 5,

        /// <summary>
        /// Enum Ignore for value: Ignore
        /// </summary>
        [EnumMember(Value = "Ignore")]
        Ignore = 6
    }

}
